### ISSUE TITLE
Unable to configure `trackingOptions`

### ISSUE THREAD

**Issue by BowlingX** [amplitude/amplitude-browser-sdk-gtm-template#31]
The `trackingOptions` property requires an object, the `normalize` function currently does not take that into account I believe:

https://github.com/amplitude/amplitude-browser-sdk-gtm-template/blob/main/template.tpl#L1166

Adjusting it to e.g.

```
const JSON = require('JSON');

// ...

// Normalize the input and return it
const normalize = val => {
  if (val === 'null') return null;
  if (val === 'true' || val === true) return true;
  if (val === 'false' || val === false) return false;
  if (val.indexOf('{') === 0) {
    return JSON.parse(val);
  }
  return makeNumber(val) || val;
};
```

Would allow to pass options like:

```
{ "ipAddress": false }
```

![image](https://github.com/amplitude/amplitude-browser-sdk-gtm-template/assets/215671/12fbd94a-18a9-4a41-8915-269c8e5fe2ff)

I'm not sure if it's possible to create a PR, then I would propose those changes.

**Comment by Mercy811** [comment]
Hi @BowlingX,  I’ve updated the template, it should take several hours for GTM to reflect the change.
