### ISSUE TITLE
Example link not working

### ISSUE THREAD

**Issue by janaengelhardt** [amplitude/amplitude-browser-sdk-gtm-template#51]
The example link in the info tooltip on the new Event properties object is leading to a 404 page

**Comment by yuhao900914** [comment]
Hi @janaengelhardt.  Thanks for choosing amplitude.
Sorry for the inconvenience.  Fix the issue in this [pr](https://github.com/amplitude/amplitude-browser-sdk-gtm-template/pull/53). 

[This](www.docs.developers.amplitude.com/data/sources/google-tag-manager-client/#event-properties-object) should be the example in our doc.
