### ISSUE TITLE
tag sequencing issue

### ISSUE THREAD

**Issue by yctwice** [amplitude/amplitude-browser-sdk-gtm-template#55]
When using a sequence of tags, you may encounter event_type and event_properties being sent incorrectly.
As ex:
In some cases I'm using tag sequencing for sending userproperties like this
![image](https://github.com/amplitude/amplitude-browser-sdk-gtm-template/assets/169830583/50d739c9-0752-4727-a552-c847a4d60b5a)
and in situations when fired a couple of events (like login+pageview or clicking on link ) i have this:
![image](https://github.com/amplitude/amplitude-browser-sdk-gtm-template/assets/169830583/8b818e8a-0427-4153-bfbb-824f85072551)
![image](https://github.com/amplitude/amplitude-browser-sdk-gtm-template/assets/169830583/2391dd04-9b4c-49f3-a460-b26fd3d70d66)
this happens, I believe, due to loss of context during sequencing

**Comment by izaaz** [comment]
@yctwice are you still running into this issue? There was a similar issue we received but it turned out to be an update in GTM and not Amplitude. So double checking if this is still an issue.
