### ISSUE TITLE
disabling "Track default Amplitude events" in init tag prevents other events from working

### ISSUE THREAD

**Issue by agohorel** [amplitude/amplitude-browser-sdk-gtm-template#65]
It appears that disabling `Track default Amplitude events` in the `Initialization` options for the `init` tag causes the tag to somehow hang and prevent subsequent events from working as expected. 

This is the part of the tag's UI I'm referring to:
<img width="318" alt="Screenshot 2024-08-27 at 4 53 31 PM" src="https://github.com/user-attachments/assets/3117e04b-3f0f-4b42-acaf-6f86180b1001">

In the GTM tag assistant it will just say "Still Running" indefinitely and I don't see any subsequent events making it to Amplitude despite appearing to fire without issue in the tag assistant UI. 
![Screenshot 2024-08-27 at 4 52 57 PM](https://github.com/user-attachments/assets/b1dbf2d6-2c8a-4748-b407-d986feefc28a)

I also noticed that even if you don't disable the entire `Track default Amplitude events` option, but just de-select one of the sub-options (ex. `Track page views`) this issue is still reproducible. 

When I revert these changes and leave it in it's default state, I see the `init` tag succeed (not hanging in the "still running" state) and I see my events flowing through as expected. Let me know if there is any useful information I can provide, thanks!

**Comment by izaaz** [comment]
@agohorel this should have been fixed in the latest gtm template. Can you please try and let us know?

**Comment by agohorel** [comment]
> @agohorel this should have been fixed in the latest gtm template. Can you please try and let us know?

@izaaz can confirm I'm no longer seeing the hanging behavior and events are flowing as expected. Thanks! 🙏
